name: ADF Build
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        adfVersion: [v2, v3]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 

      - name: Set up Azure PowerShell
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

 
      - name: Create ADF
        id: create-adf
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az group create --name aargadfmatrix --location 'East US'
          az datafactory create --name aamatrixadf --resource-group aargadfmatrix --location 'East US' --version ${{ matrix.adfVersion }}

 
      - name: Display ADF Information
        run: |
          echo "ADF Version: ${{ matrix.adfVersion }}"
          echo "ADF Name: ${{ steps.create-adf.outputs.name }}"
          echo "ADF Resource Group: ${{ steps.create-adf.outputs.resourceGroupName }}"
