name: ADF Deployment
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: 'This deploys to Production'
    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: Azure/login@v1.4.3
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.6
      with:
       
        scope: 'resourcegroup'
        resourceGroupName: 'adf-resources'
        template: ./testrepo/ARMTemplateParams.json
        deploymentMode: Incremental
        parameters: factoryName=aaadf23
